//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentTaskModelModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParentTaskModelModule()
        {
            this.TaskModelModules = new HashSet<TaskModelModule>();
        }
    
        public int ParentTaskId { get; set; }
        public string ParentTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskModelModule> TaskModelModules { get; set; }
    }
}
