//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModelModule
    {
        public int TaskId { get; set; }
        public string TaskDescripton { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
    
        public virtual ParentTaskModelModule ParentTaskModelModule { get; set; }
    }
}
